[package]
name = "git2-rs-rebase-example"
version = "0.1.0"
authors = ["Robin Stocker <robin@nibor.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "*"
